name: cosmrs

on:
  push:
    branches: main
  pull_request:
    paths:
      - ".github/workflows/cosmrs.yml"
      - "cosmos-sdk-proto/**"
      - "cosmrs/**"
      - "Cargo.*"

defaults:
  run:
    working-directory: cosmrs

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Dwarnings
  RUSTDOCFLAGS: -Dwarnings

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - 1.88.0 # MSRV
        target:
          - x86_64-unknown-linux-gnu
          - wasm32-unknown-unknown
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803
        with:
          persist-credentials: false
      - uses: dtolnay/rust-toolchain@6c977a6ca4077a0ceb28ffbe03f59d46e9ac8772
        with:
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.target }}
      - run: cargo build --target ${{ matrix.target }} --no-default-features --release

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - 1.88.0 # MSRV
          - stable
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803
        with:
          persist-credentials: false
      - uses: dtolnay/rust-toolchain@6c977a6ca4077a0ceb28ffbe03f59d46e9ac8772
        with:
          toolchain: ${{ matrix.rust }}
      - run: cargo test --release --no-default-features
      - run: cargo test --release
      - run: cargo test --release --all-features

  doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803
        with:
          persist-credentials: false
      - uses: dtolnay/rust-toolchain@6c977a6ca4077a0ceb28ffbe03f59d46e9ac8772
        with:
          toolchain: stable
      - run: cargo doc --all-features
