name: proto-build

on:
  push:
    branches: main
  pull_request:
    paths:
      - ".github/workflows/proto-build.yml"
      - "proto-build/**"
      - "Cargo.*"

defaults:
  run:
    working-directory: proto-build

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Dwarnings

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803
        with:
          persist-credentials: false
      - run: cargo build --verbose
      - run: cargo test --verbose
